import type { InstagramFeedItem } from "./instagram-types";

const PROFILE_URL = "https://www.instagram.com/westcoastbeauty.co/";

export const FALLBACK_INSTAGRAM_ITEMS: InstagramFeedItem[] = [
  {
    id: "fallback-1",
    permalink: PROFILE_URL,
    caption: "Behind the scenes at West Coast Beauty Co.",
    timestamp: "2026-03-03T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-19.jpg",
    children: [],
  },
  {
    id: "fallback-2",
    permalink: PROFILE_URL,
    caption: "Student special smiles and results.",
    timestamp: "2026-03-06T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-7.jpg",
    children: [],
  },
  {
    id: "fallback-3",
    permalink: PROFILE_URL,
    caption: "Curated ear stacks and signature sparkle.",
    timestamp: "2026-03-09T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-29.jpg",
    children: [],
  },
  {
    id: "fallback-4",
    permalink: PROFILE_URL,
    caption: "A little studio moment from this week.",
    timestamp: "2026-03-12T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-62.jpg",
    children: [],
  },
  {
    id: "fallback-5",
    permalink: PROFILE_URL,
    caption: "Wellness event recap and elevated details.",
    timestamp: "2026-03-15T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-64.jpg",
    children: [],
  },
  {
    id: "fallback-6",
    permalink: PROFILE_URL,
    caption: "Something beautiful is blooming in the studio.",
    timestamp: "2026-03-18T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/543A2834.jpg",
    children: [],
  },
  {
    id: "fallback-7",
    permalink: PROFILE_URL,
    caption: "Fresh set, fresh confidence.",
    timestamp: "2026-03-20T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-94.jpg",
    children: [],
  },
  {
    id: "fallback-8",
    permalink: PROFILE_URL,
    caption: "Event days with the West Coast Beauty crew.",
    timestamp: "2026-03-22T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-48.jpg",
    children: [],
  },
  {
    id: "fallback-9",
    permalink: PROFILE_URL,
    caption: "Honored to support community and wellness.",
    timestamp: "2026-03-24T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-72.jpg",
    children: [],
  },
  {
    id: "fallback-10",
    permalink: PROFILE_URL,
    caption: "Signature ear curation close-up.",
    timestamp: "2026-03-26T18:00:00.000Z",
    mediaType: "IMAGE",
    thumbnailUrl: null,
    mediaUrl: "/Westcoastbeauty-8.jpg",
    children: [],
  },
];

export function getFallbackInstagramItems(limit: number): InstagramFeedItem[] {
  return FALLBACK_INSTAGRAM_ITEMS.slice(0, limit);
}
